### ISSUE TITLE
Improvement of readability on 'Development and Contributing' section on README.md

### ISSUE THREAD

**Issue by kaestro** [tarto-dev/tagsy-discord#39]
For my reading was not that good, I had hard time figuring out where my discord bot token is.

I think it would be of help to those like me, if we could split the document in three steps

1. 4ways of contributing to the project
2. how to set up development environment
  a. How to attain discord bot token
3. Thins to be careful of

**Comment by kaestro** [comment]
@tarto-dev BTW, I'm having hard time running the bot.py itself for right now.

I've set up .env as follows(I've resetted the token for now)

![image](https://github.com/tarto-dev/tagsy-discord/assets/32026095/0ade8f12-9245-4780-abdf-d93a04282716)
![image](https://github.com/tarto-dev/tagsy-discord/assets/32026095/aeb353c3-dba4-4fa2-91c6-8506df8961a0)

Is there anything I'm doing in a wrong way? I'm getting this error

    raise LoginFailure("Improper token has been passed.") from exc
disnake.errors.LoginFailure: Improper token has been passed

**Comment by tarto-dev** [comment]
It is weird. I just tried by reseting an old bot token, insert it into .env then start bot, and didn't got this error.
Can you reset your bot token over Discord then reset the .env file with the newer token ?

**Comment by tarto-dev** [comment]
BTW i'm sure improving doc would be very helpful but still hard to me, since I started the project, hard to me to say where it's hard.

I'll use your experiments on this to update it. 

Let's keep that issue open until you succeed

**Comment by kaestro** [comment]
I've tried resetting the token. I'll try some other methods whether which one's problematic and let you know when I got it done or have some questions

**Comment by tarto-dev** [comment]
Even with refreshed token you continue to get that error ?

**Comment by kaestro** [comment]
Yes, I've just tried and got same error.
Maybe I need to start from bottom and read through the manual again

**Comment by tarto-dev** [comment]
Quick and dirty doc would say :

- copy .env.example to .env
- put in .env the discord bot token
- install dependencies (pip install -r dev-requirelents.txt)
- start python bot.py

**Comment by kaestro** [comment]
first of all, you're correct with 3rd one. I only installed requirements, not the dev-requirements.

Is there any documentation that notifies it? because my read-me only shows to

```
pip install -r requirements.txt
```

Also, it seems there needs some more work on giving privilege with bot for this error started to come out

  File "C:\Users\didme\Documents\repositories\tagsy-discord\venv\Lib\site-packages\disnake\client.py", line 992, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
disnake.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is 
recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not 
possible, then consider disabling the privileged intents instead.

**Comment by kaestro** [comment]
I might be a bit late for the next reply for I'm about to go for a work out and have dinner

**Comment by tarto-dev** [comment]
You right about intent ! enable `MESSAGE CONTENT INTENT` to let shortcode works, but bot should start even if not enabled. 

But not sure about the ShardID intent privilege error. Ssince bot isn't sharded right now, It is used to helps bot to scale, not the case at this moment. 

For your bot invite link (and ensure we got the same rights, either check administrator (=8) or use the public permissions (=277025451008)

**Comment by tarto-dev** [comment]
> I might be a bit late for the next reply for I'm about to go for a work out and have dinner

Sure, just noticed the 7h ahead timezone ^^

GN, take care

**Comment by kaestro** [comment]
@tarto-dev 

I'm not sure of why, but checking only the last two enabled to run the bot.py. But there seems no problem with checking all three of them. I guess updating this on a document would be of help just like modifying requirements.txt to dev-requirements.txt

![image](https://github.com/tarto-dev/tagsy-discord/assets/32026095/30f2343e-452b-4b57-9636-a0abe9967be3)

**Comment by tarto-dev** [comment]
> @tarto-dev 
> 
> I'm not sure of why, but checking only the last two enabled to run the bot.py. But there seems no problem with checking all three of them. I guess updating this on a document would be of help just like modifying requirements.txt to dev-requirements.txt
> 
> ![image](https://github.com/tarto-dev/tagsy-discord/assets/32026095/30f2343e-452b-4b57-9636-a0abe9967be3)
> 

It is weird, and I did not enable all in production as I prefer using right amount of permission rather than '' all permissions but not all used''.

I am against Android games asking to read Phone history or Location, I tend to apply same logic when I can in programming ^^

But for a local instance, it is not a big deal afaik

**Comment by kaestro** [comment]
I totally agree with the idea that enabling permissions as little as possible is needed. Maybe there's some other way through this problem but for now, to start working on some issues I'll let this go by.
