### ISSUE TITLE
Content doesn't retain text formatting (Ulteura uregentooo !!!)

### ISSUE THREAD

**Issue by WegPast** [tarto-dev/tagsy-discord#4]
Added command "cat" with :
```
  /\_/\  (
 ( ^.^ ) _)
   \"/  (
 ( | | )
(__d b__)
```
and got this 
![image](https://github.com/tarto-dev/tagsy-discord/assets/9842726/ace1f716-c768-412b-96bc-5ee63ed517c7)

Same with MarkDown : only Bold and Italic are saved. Newlines and list are not rendered

**Comment by tarto-dev** [comment]
It's now fixed #10 (replace old add by a modal)
