### ISSUE TITLE
Adjustments on comments

### ISSUE THREAD

**Issue by kaestro** [tarto-dev/tagsy-discord#41]
@tarto-dev 

It is really great that there's well written comments on every each methods. I'm really amazed and thank you for your endeavor.

The problem is, I think it needs some adjustments for I believe this is harming my readability of the code for right now.

For example

![image](https://github.com/tarto-dev/tagsy-discord/assets/32026095/4566b437-fd84-471f-a7d4-aba28d2b2297)

I believe these changes might improve readability and reduce the comments.

1. rename variable inter's name interaction
2. write Nonetype inside the python method itself

```python
async def get(...) -> None:
```

3. Remove comment 'Retrieves and displays a tagged message from the database' and put it inside description.

I know it would be really hurtful that I can see that you've put hard work on these comments, but it makes me hard to read and append new codes for now.

If you don't mind, I need to changes on this comments for me to implement new command for get all tags from author.

Thank you

**Comment by tarto-dev** [comment]
Hey ! What do you mean by `it makes me hard to read and append new codes for now.` ?

Feel free to update if needed 😊

**Comment by tarto-dev** [comment]
1. About the variables refactor, nice thing to do, wasn't bothering when I was alone, but makes sence now.

2. We could even implements sole Mypy '' hard typing'' to enhance code strengh and overall quality, lmk if this would helps you.

3. Description and code comments does not cover same population, I am OK to edit description but not to remove it from comment as my IDE read comment and not description 😊

**Comment by kaestro** [comment]
> Hey ! What do you mean by `it makes me hard to read and append new codes for now.` ?
> 
> Feel free to update if needed 😊

I wish my English were much better. I was trying to say that it's rather hard for me to implement new methods to the source codes for now.

The reason is that I was trying to read the previous codes and follow first, but for comments being in the middle of method initialization and implementation, I had hard time finding out what the method was trying to do because I couldn't see them in one page. Maybe it's because you might have much taller screen than what I have.

1. Then I'll try working on it with tag_command first and implement 'get all tags'

2. I haven't used Mypy hard typing yet and my only experience was on using things like these

```python
from typing import List, Tuple
```

but seems really interesting. I'll try applying it when I have time.

3. I couldn't understand what you're trying to say. What do you mean by 'Description' and 'comments?

**Comment by tarto-dev** [comment]
> I couldn't understand what you're trying to say. What do you mean by 'Description' and 'comments?

As you may have noticed, the decorator comes with `description` argument, which is really close to the message put within code comment. 

The `description` is used by discord-slash-commands-aggregator who will put that information to user, where the code-comment will only be shown to developers/maintainers (mainly through their IDE), that's why message may be redundant but needed

**Comment by kaestro** [comment]
> > I couldn't understand what you're trying to say. What do you mean by 'Description' and 'comments?
> 
> As you may have noticed, the decorator comes with `description` argument, which is really close to the message put within code comment.
> 
> The `description` is used by discord-slash-commands-aggregator who will put that information to user, where the code-comment will only be shown to developers/maintainers (mainly through their IDE), that's why message may be redundant but needed

Ah, I got it! thank you for your explanataion
